#!/bin/sh
#
#       /etc/rc.d/init.d/wdmeeting
#
#       Runs the wdmeeting
#
#
# chkconfig:   - 85 15
#

### BEGIN INIT INFO
# Provides:          wdmeeting
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      mysql
# Should-Stop:       mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start wdmeeting at boot time.
# Description:       Control wdmeeting.
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Default values

NAME=wdmeeting
APP_HOME=/app/wdmeeting
APP_PATH=${APP_HOME}/$NAME
APP_USER=www
SERVICENAME="wdmeeting"
LOCKFILE=/var/lock/subsys/wdmeeting
LOGPATH=${APP_HOME}/log
LOGFILE=${LOGPATH}/wdmeeting.log
RETVAL=0

[ -r /etc/sysconfig/$NAME ] && . /etc/sysconfig/$NAME

[ -x ${APP_PATH} ] || exit 0
[ -x ${LOGPATH} ] || exit 0

DAEMON_OPTS="--check $NAME"

# Set additional options, if any
[ ! -z "$APP_USER" ] && DAEMON_OPTS="$DAEMON_OPTS --user=${APP_USER}"

start() {
  cd ${APP_HOME}
  echo -n "Starting ${SERVICENAME}: "
  daemon $DAEMON_OPTS "${APP_PATH} web > ${LOGFILE} 2>&1 &"
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && touch ${LOCKFILE}

  return $RETVAL
}

stop() {
  cd ${APP_HOME}
        echo -n "Shutting down ${SERVICENAME}: "
        killproc ${NAME}
        RETVAL=$?
        echo
        [ $RETVAL = 0 ] && rm -f ${LOCKFILE}
}

case "$1" in
    start)
        status ${NAME} > /dev/null 2>&1 && exit 0
        start
        ;;
    stop)
        stop
        ;;
    status)
        status ${NAME}
        ;;
    restart)
        stop
        start
        ;;
    reload)
        stop
        start
        ;;
    *)
        echo "Usage: ${NAME} {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
