/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DeviceOption: typeof import('./components/webrtc/DeviceOption.vue')['default']
    DeviceSelect: typeof import('./components/webrtc/DeviceSelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FileButton: typeof import('./components/webrtc/PeerWhiteboard/FileButton.vue')['default']
    PeerActions: typeof import('./components/webrtc/PeerActions.vue')['default']
    PeerAudioOutput: typeof import('./components/webrtc/PeerAudioOutput.vue')['default']
    PeerStatusBar: typeof import('./components/webrtc/PeerStatusBar.vue')['default']
    PeerTools: typeof import('./components/webrtc/PeerTools.vue')['default']
    PeerVolumeBar: typeof import('./components/webrtc/PeerVolumeBar.vue')['default']
    PeerWhiteboard: typeof import('./components/webrtc/PeerWhiteboard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenSources: typeof import('./components/webrtc/ScreenSources.vue')['default']
    SwalDialog: typeof import('./components/webrtc/SwalDialog/index.vue')['default']
    Whiteboard: typeof import('./components/webrtc/Whiteboard/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
